name: tests c++20

on:
  push:
  pull_request:

jobs:
  test-linux:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        compiler: [g++-10, clang++-12]
        target: [debug, release]
    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: |
           python3 -m pip install --upgrade pip
           python3 -m pip install git+https://github.com/jeffkaufman/icdiff.git
    - name: build library
      run: make COMPILER=${{matrix.compiler}} TARGET=${{matrix.target}} STD=c++20
    - name: build tests
      working-directory: tests
      run: make tests COMPILER=${{matrix.compiler}} TARGET=${{matrix.target}} STD=c++20
    - name: dos2unix
      working-directory: tests/integration/expected
      run: |
           sudo apt install dos2unix
           dos2unix *.txt
    - name: run tests
      working-directory: tests
      run: python3 run-tests.py --compiler=${{matrix.compiler}} --build_type=${{matrix.target}} --integration
  test-msvc:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        target: [debug, release]
    steps:
    - uses: actions/checkout@v2
    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.10.0
    - name: dependencies
      run: |
           python3 -m pip install --upgrade pip
           python3 -m pip install git+https://github.com/jeffkaufman/icdiff.git
    - name: build library
      run: make COMPILER=msvc STD=c++20
    - name: build tests
      working-directory: tests
      run: make tests COMPILER=msvc STD=c++20
    - name: dos2unix
      working-directory: tests/integration/expected
      run: dos2unix *.txt
    - name: run tests
      working-directory: tests
      run: python3 run-tests.py --compiler=msvc --build_type=${{matrix.target}} --integration
  # TODO: Not currently testing g++ or clang release on windows
  #test-gcc-windows-cpp20: # currently addr2line is not working, not sure why
  #  runs-on: windows-2019
  #  steps:
  #  - uses: actions/checkout@v2
  #  - uses: msys2/setup-msys2@v2
  #    with:
  #      install: mingw-w64-x86_64-gcc mingw-w64-x86_64-binutils mingw-w64-x86_64-python make git dos2unix diffutils
  #  - name: dependencies
  #    shell: msys2 {0}
  #    run: |
  #         git clone https://github.com/jeffkaufman/icdiff.git
  #         cp -avp icdiff/icdiff tests/
  #  - name: build library
  #    shell: msys2 {0}
  #    run: make COMPILER=g++ STD=c++20
  #  - name: build tests
  #    shell: msys2 {0}
  #    working-directory: tests
  #    run: make tests COMPILER=g++ STD=c++20
  #  - name: dos2unix
  #    shell: msys2 {0}
  #    working-directory: tests/integration/expected
  #    run: dos2unix *.txt
  #  - name: run tests
  #    shell: msys2 {0}
  #    working-directory: tests
  #    run: |
  #          export PATH=$PATH:$(pwd)
  #          nm bin/integration.exe
  #          python run-tests.py gcc_windows
  test-clang-windows-cpp20:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: |
           python3 -m pip install --upgrade pip
           python3 -m pip install git+https://github.com/jeffkaufman/icdiff.git
    - name: build library
      run: make COMPILER=clang++ STD=c++20
    - name: build tests
      working-directory: tests
      run: make tests COMPILER=clang++ STD=c++20
    - name: dos2unix
      working-directory: tests/integration/expected
      run: dos2unix *.txt
    - name: run tests
      working-directory: tests
      run: python3 run-tests.py --compiler=clang_windows --integration
